### ISSUE TITLE
Option to disable W. Tails remaining stickers chat notification doesn't work

### ISSUE THREAD

**Issue by e-mts** [MidoriKami/DailyDuty#111]
This is a weekly task, I'd like to have the option to disable this notification so that it works as before but it doesn't work currently. The current workaround is turning off this notification on zone change but I don't want to do that since I do want to be reminded about picking up the weekly journal.

![image](https://user-images.githubusercontent.com/61860605/230635668-e334ad3f-b820-49bc-8c4b-56f7ad5c7f8d.png)

**Comment by MidoriKami** [comment]
Fixed in 0d8afec5196d14896208a637da91f7e5b958d444

**Comment by e-mts** [comment]
TYVM!

**Comment by MidoriKami** [comment]
I misinterpreted your request, the bugs that were noted as fixed were regarding notifications being sent even with the module being disabled.

It is intentional to have a # Stickers Remaining notification with every zone change if zone change notifications are on. The purpose of DailyDuty is to pester the user to complete the module. The old behavior did not accomplish this goal.
