### ISSUE TITLE
Treasure Map not tracking properly

### ISSUE THREAD

**Issue by githubuser14937** [MidoriKami/DailyDuty#123]
Since the update, the treasure map module doesn't update at all. It keeps saying my last map gathered was at 0001-01-01 12:00:00 AM. I tried gathering both lv. 70 and 60 maps. Is it just set to account for lv 90 maps?
![image](https://user-images.githubusercontent.com/124318201/230785594-a0ad1c02-ff26-4157-b9ae-5d074a02e801.png)

**Comment by MidoriKami** [comment]
Any chance you could attach a video of you gathering a map the next time one is available?

**Comment by githubuser14937** [comment]
okok, will do!

**Comment by MidoriKami** [comment]
The issue here is DailyDuty uses chat messages for tracking when you have gathered a Treasure Map, TidyChat is suppressing that message preventing DailyDuty from seeing it.
I am working on an alternative tracking method for this module.

The Raids (Alliance) and Raids (Normal) will likely have similar issues.

**Comment by MidoriKami** [comment]
While you are waiting for this fix to be released, disable Tidy Chat's blocking of Gathering Messages.
The fix won't be released anytime soon, I am working on several other things currently.

**Comment by githubuser14937** [comment]
okok, thanks!
