### ISSUE TITLE
Wondrous Tales feature request

### ISSUE THREAD

**Issue by Dracoman13** [MidoriKami/DailyDuty#127]
I would like to have the option to have DD automatically stop notifying me once I've placed 7 stickers and have two waiting to be placed. I usually want to wait until the next week to put down the last two stickers on the off chance that I get enough second chances for good shuffles, but there's no option to make DD stop alerting me without using the snooze feature.

**Comment by MidoriKami** [comment]
It is intentional to have a # Stickers Remaining notification with every zone change if zone change notifications are on. The purpose of DailyDuty is to pester the user to complete the module. Your book is in fact still incomplete, therefore DailyDuty will send you notifications to complete it.

The Snooze feature is designed for edge cases like this.
