### ISSUE TITLE
This forced update is horrible. 

### ISSUE THREAD

**Issue by Astral-Crescent** [MidoriKami/DailyDuty#136]
I don't understand why you would remove such an important feature as click to drag around. I am constantly resizing my windows and this ruins it for me. Also shoving a bunch of crap at me I don't want and can't figure out how to get of my tasks that I never asked for that I didn't consent to? When you push dev updates, remember that your users can't CONSENT to it. I can't figure out where ANYthing is anymore. The previous version I understood fine.  I have to uninstall now because you ruined the entire plugin. Unbelievable.

**Comment by MidoriKami** [comment]
> I don't understand why you would remove such an important feature as click to drag around
lol? The feature was completely re-implemented using native game element code to be a seamless part of the game UI.
Due to technical reasons that you likely wouldn't understand there is no reasonable way to make a native UI element "click-to-drag"

There are several benefits to being a native UI element, and several features that will be released in the new future will take advantage of more of these benefits.
It's easy to complain when you don't understand how any of this works.

> When you push dev updates, remember that your users can't CONSENT to it.
Nothing I have released is *harmful* by any measure. Often automatically enabling these features is my only way to signal to users "hey, new stuff here you might like it". And if you don't like it, it's a single check box to turn it off.

>  I have to uninstall now
No worries, it's free software, you're free to use or not use it as you please.
