### ISSUE TITLE
Wondrous Tales Feature Request

### ISSUE THREAD

**Issue by Dracoman13** [MidoriKami/DailyDuty#143]
Can you add the option in Wondrous Tales to just receive alerts when there is an unclaimed book and/or second chances are nearing their limit? I don't need to always know that my current book is unfinished, but those two in particular are something I always want to be notified of. Also, adding some additional clarity on the "Shuffle Available Notice" tooltip that says specifically when it notifies you. The text implies that it will notifies you when it's "near" the limit, and I'd prefer that I just get notified when it's at 9, and I'm not sure if that's the case.

**Comment by MidoriKami** [comment]
It is intentional to have a # Stickers Remaining notification with every zone change if zone change notifications are on. The purpose of DailyDuty is to pester the user to complete the module. Your book is in fact still incomplete, therefore DailyDuty will send you notifications to complete it.

You can check the code to see the specific conditions for a notification.
https://github.com/MidoriKami/DailyDuty/blob/master/DailyDuty/System/Modules/WondrousTails.cs#L192
