### ISSUE TITLE
Feature Request: track weekly capped tomestones

### ISSUE THREAD

**Issue by coredumperror** [MidoriKami/DailyDuty#151]
Would it be possible to add a Weekly Task that tells you if you still need to earn any Allaagan Tomestones of Comedy (or whatever the currently weekly-capped tomestone is) in the current week? That'd be quite handy.

**Comment by MidoriKami** [comment]
No, this is already a part of the Duty Roulette module.

DailyDuty tracks actual tasks, not goals.

**Comment by coredumperror** [comment]
Ohhh, thanks! I didn't know about that module.

**Comment by LuminaSapphira** [comment]
Going to necro this thread to mention I implemented this in a personal fork since I like having a nice reminder to cap my tomes. It felt weird to have it bound to duty roulette if there are other ways to get tomes (namely hunt trains). 

If @MidoriKami has changed their mind on this I'm happy to open a PR upstream. Otherwise, I don't intend to open a PR for this branch, or release the fork in any compiled fashion.
