### ISSUE TITLE
Savage Raid Module

### ISSUE THREAD

**Issue by Ivinedra** [MidoriKami/DailyDuty#197]
I have added a module to track weekly savage raid drops. Module is live on my fork and build successfully loaded into game. Will confirm full functionality with the release of savage. Will create a PR if this module is desired.

**Comment by MidoriKami** [comment]
I have no intention of tracking Savage Raids in DailyDuty.

The intention of DailyDuty is to *remind* people to do things that they would otherwise forget to do. Savage does not fall into this category, as a vast majority of players will opt to do Savage with pre-arranged groups.

Additionally, it's also my intent that DailyDuty's tasks tend towards the casual players, I don't want DailyDuty to appear to push people into content that they might not want to do.

**Comment by MidoriKami** [comment]
Posting here is entirely fine 👍
