### ISSUE TITLE
Wondrous Tails sticker messages

### ISSUE THREAD

**Issue by engiwengi** [MidoriKami/DailyDuty#229]
Were sticker messages removed in 57d1b3bd40a9adab0ed43f8b26043e286d07c6d1 because they weren't working or an actual choice? Probably my favourite feature in this plugin and sad to see it go. Hoping this is just temporary.

**Comment by MidoriKami** [comment]
Intentionally removed, square enix has significantly redesigned the Wondrous Tails system each patch for the last 4 major patches. I design my plugins to be self-sufficient and self-updating so that the maintenance burden is low. This ensures that even if I were to completely vanish, my plugins could continue to exist with minimal effort.

With them constantly changing the system there's no way for me to write code that would automatically accommodate the changes each patch.

Other plugins such as WTSync have continued my work, and implemented these features as a part of their plugin. I'm simply unwilling to commit to such a maintenance burden.

**Comment by MidoriKami** [comment]
As a fun side note, I was the first person to reverse engineer the Wondrous Tails tasks system, and it was my first time reverse engineering anything. My Ko-Fi profile page shows a screenshot of the raw memory that represents the tasks data.
