### ISSUE TITLE
[Bug] Duty Completion resetting when changing characters

### ISSUE THREAD

**Issue by Jackalune** [MidoriKami/DailyDuty#29]
Duty completion resets (overwrites?) for one character when logging into an alternate character, then back to the first.

Steps to reproduce:
1. Log in to Character A, complete a tracked Daily Duty task (they are properly flagged completed at this point)
2. Log in to Character B (which has NOT completed this task); do not complete the task, do not have previous completion of the task that day
3. Log back into Character A
The tasks will have been changed to incomplete on character A.

I have tested this with a fresh config file and confirmed it is happening with Mini Cactpot, Custom Deliveries, and Fashion Report.
Oddly, Jumbo Cactpot and Duty Roulette do not seem to "reset"/overwrite for Character A. 
I have not tested other duties at this time.

Additionally, configs related to addon _display_ (such as showing/hiding Todo Window) _seem_ to be preserved per-character when changing between Character A and B.

Please let me know if I can provide further information or testing!

**Comment by MidoriKami** [comment]
> Additionally, configs related to addon display (such as showing/hiding Todo Window) seem to be preserved per-character when changing between Character A and B.
I have two sets of configurations, CharacterSettings and the more generalized global settings. The Global Settings shouldn't have any issues.

**Comment by MidoriKami** [comment]
See:
https://github.com/MidoriKami/DailyDuty/blob/master/DailyDuty/Data/Configuration.cs
For more information on how the save file is setup.

**Comment by MidoriKami** [comment]
Thank you for your help in finding a repeatable test scenario to find the problem!

The issue is when one module resets, it resets that module for all characters, even if the other characters don't need to be reset!

The reason it doesn't happen for Jumbo Cactpot and Duty Roulette is due to a typo... In those modules I reference "Settings" the variable for the specific character you are logged in to, not "settings" which represents all characters settings. xD
