### ISSUE TITLE
[Bug] Treasure Map

### ISSUE THREAD

**Issue by Speshkitty** [MidoriKami/DailyDuty#44]
Treasure map tracker is not detecting the timer correctly when a map was gathered before the addon was installed, and I cannot manually set the timer.

Image taken with edit mode on

![image](https://user-images.githubusercontent.com/1111285/164677068-b3aef08d-057f-46ea-96e8-1d17b4129d0f.png)

**Comment by MidoriKami** [comment]
That is correct. As noted in that popup window that appeared when you installed the plugin, not everything is recorded automatically. Treasure Maps are one such thing. There is no edit mode provided because this is the ***only*** scenario in which treasure maps are not tracked correctly. From tomorrow onwards your treasure maps will be tracked without issue.
