### ISSUE TITLE
Hunt Marks (Daily)

### ISSUE THREAD

**Issue by Evolutious** [MidoriKami/DailyDuty#58]
Good day - Just wanted to advise that the Hunt Marks (Daily) remains in a completed state each day even though I have not completed them yet for the day.

In the below, I have completed my Hunt Marks (weekly) but have not completed my Hunt Marks (Daily) for today (I did complete the Daily yesterday though).
![image](https://user-images.githubusercontent.com/49498530/166962468-20588e46-0ad9-436d-8d24-1c17f78839bf.png)

**Comment by MidoriKami** [comment]
What version are you on

**Comment by Evolutious** [comment]
![image](https://user-images.githubusercontent.com/49498530/167042577-5cf386a7-2372-47a7-8099-6fc1bf39567a.png)

**Comment by Evolutious** [comment]
By the way, it still shows Hunt Marks (Daily) as complete but i still have not done them today; they are still in my Key Items bag. I am happy to test anything if you would like.

**Comment by MidoriKami** [comment]
Send you character .json and your character .log that is located in PluginConfigs\DailyDuty

**Comment by Evolutious** [comment]
Where would you like for me to send them?

**Comment by Evolutious** [comment]
[18014498564973417.zip](https://github.com/MidoriKami/DailyDuty/files/8636644/18014498564973417.zip)

**Comment by MidoriKami** [comment]
Ohh I think I know what happened. There was a bug where I had Hunt Marks (Daily) set to be a weekly by accident, and so your Hunt Marks Daily tried to do a "weekly reset" and set it's next reset date to be next week. This bug was fixed already, but the reset date that it saved was incorrect and is having lasting effects.

I see that it hasn't triggered an update correctly from your .log
![image](https://user-images.githubusercontent.com/9083275/167044778-5c4d72f4-115e-409c-bb4f-07ff502aaedf.png)

Then I see in your .json that the next reset date is scheduled for the 10th `    "NextReset": "2022-05-10T08:00:00Z",`
Simply delete line 257 from your .json while you are not logged into that character, and it should fix itself.

**Comment by Evolutious** [comment]
I deleted the line, logged in and it looks good now. I will let you know if it has any issues tomorrow after reset, but sounds like this was just a left over artifact of the previous bug. 

![image](https://user-images.githubusercontent.com/49498530/167048536-3f3f59dc-7c51-41ab-bc95-ba7415458a57.png)

Thanks!
