### ISSUE TITLE
Feedback on v3.0.0.1

### ISSUE THREAD

**Issue by Sevii77** [MidoriKami/DailyDuty#81]
This is based on the open pull request v3.0.0.1 e95d8cbc77215d4d80b656df03f18231df9c8a35

- Inner module seperate tasks aren't spaced the same as module tasks themselves.
![image](https://user-images.githubusercontent.com/20374966/186892420-1e583759-4016-436f-b7fc-0d76680a6139.png)
- Having timers for weekly and daily would be nice, as I personally find having the same timers but named differenty for duties bulky, and only having 1 enabled is confusing as it would be the name of said duty.
- Timers no longer have the shorter name option.
- The Timer display options with Day have a leading 0 when it can never be double digits, i personally prefer `:` over `.` as a day seperator, and days are shown even if the timer is <24H. Maybe a `Custom` option that allows the user to use a string formatter would be the solution as this allows everyone to have it the way they prefer it but this might not be worth the effort.
- Having a button for `Edit Timers` and `Edit Todo` in the main configuration menu would be nice as that avoids having to look through the chat help menu and allows the user to open all configurations from the plugin installer (The gear button).
- Duty Roulette Export Hide seems to be missing a translation string for english
![image](https://user-images.githubusercontent.com/20374966/186898440-367d0cd8-046a-42d7-a3e7-7d3b3214d9ab.png)

**Comment by MidoriKami** [comment]
Inner module task spacing is intentional. It gives a very nice slight visual separation to the categories.

I can add a daily and weekly reset pretty easily, I'll do that.

This version uses the modules localization strings for display, it's consistent across the whole plugin, I'm considering adding a "custom name" option that displays what the user inputs instead.

The day followed by dot is standardized formatting, additionally I like keeping the zero as it indicates to the user that the specific timer has a period longer than a day. https://docs.microsoft.com/en-us/dotnet/standard/base-types/standard-timespan-format-strings

I want to keep the UI clean and simple, however I definitely do want buttons or something to do that, but haven't figure out a decent way to make it not look terrible.

Nice catch on the string I was a bit hasty with the pr because I wanted to sleep lol.

**Comment by MidoriKami** [comment]
Thanks for the comprehensive feedback btw!

**Comment by Sevii77** [comment]
As a end user I mostly care about the tasks I still have left to do, and don't think about what category it's from. Perhabs a option to allow it to be spaced like a category or compacted into a single category might be worth.

**Comment by MidoriKami** [comment]
> Can you please add back the toggle command to turn the todo/timer window on/off? With the current show and hide commands you would need 2 macros for toggling
> 
> Btw I personally found the old design of the whole plugin much better

Those missing commands were an oversight, they are readded now.
Added navigation buttons to get to the other windows.

I will ignore all "I liked the old way better" posts, if you have constructive feedback please describe in detail what you like or dislike.
